# Generated by Django 2.2.2 on 2019-08-27 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('F', '女'), ('M', '男'), ('O', '其他')], default='F', max_length=2, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('register_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='注册日期')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('prescription', models.TextField(verbose_name='配方')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='来访日期')),
                ('symptom', models.TextField(blank=True, null=True, verbose_name='症状')),
                ('dose_num', models.IntegerField(verbose_name='份数')),
                ('prescription', models.TextField(verbose_name='处方')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Patient', verbose_name='姓名')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.PrescriptionTemplate', verbose_name='方剂')),
            ],
        ),
    ]
